# Generated by Django 3.2.9 on 2022-01-24 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Mobile', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_type', models.CharField(max_length=200)),
                ('Desc', models.TextField(max_length=1200)),
                ('Image', models.ImageField(upload_to='family_images')),
                ('Food', models.CharField(max_length=200)),
                ('Decoration', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_type', models.CharField(max_length=200)),
                ('Desc', models.TextField(max_length=1200)),
                ('Image', models.ImageField(upload_to='culture_images')),
                ('Food', models.CharField(max_length=200)),
                ('Decoration', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_type', models.CharField(max_length=200)),
                ('Desc', models.TextField(max_length=1200)),
                ('Image', models.ImageField(upload_to='charity_images')),
                ('Food', models.CharField(max_length=200)),
                ('Sponser', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_type', models.CharField(max_length=200)),
                ('Desc', models.TextField(max_length=1200)),
                ('Image', models.ImageField(upload_to='bussiness_images')),
                ('Food', models.CharField(max_length=200)),
                ('Publicity', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Mobile', models.IntegerField()),
                ('Loaction', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Pepole', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Event', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=1200)),
                ('Message', models.TextField(max_length=1200)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
