# Generated by Django 3.2.9 on 2022-01-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0002_alter_contactus_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='Image',
            field=models.ImageField(upload_to='static/family_images'),
        ),
    ]
