# Generated by Django 3.2.9 on 2022-02-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0003_alter_family_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='Mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='Image',
            field=models.ImageField(upload_to='static/image/bussiness_images'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='Image',
            field=models.ImageField(upload_to='static/image/ulture_images'),
        ),
        migrations.AlterField(
            model_name='family',
            name='Image',
            field=models.ImageField(upload_to='static/image/family_images'),
        ),
    ]
