# Generated by Django 3.2.9 on 2022-02-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0004_auto_20220204_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
